[package]
name = "key-translator"
version = "0.1.0"
authors = ["victor.fedorenko <victor.fedorenko@mgid.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
