on: [push, pull_request]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0
      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: 22116/clipboard-translator
          tag: latest
          registry: hub.docker.com
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}