name: .
version: "1.0"
subcommands:
  - translate:
      about: Show translated text from clipboard as notification
      args:
        - primary-lang:
            short: p
            help: Target language to translate
            required: true
            takes_value: true
            index: 1
        - secondary-lang:
            short: s
            help: Language used to fallback translation
            required: false
            takes_value: true
            index: 2
        - translator:
            short: t
            help: "Translator used. Available translators: 'Google'"
            required: false
            takes_value: true
            index: 3
        - not-notify:
            short: n
            help: Do not send the system notification with translated text
            required: false
        - selected:
            help: Translate selected text instead of text from clipboard. Requires 'xsel' module on the system to be installed
            required: false
