name: .
version: "1.0"
subcommands:
  - translate:
      about: Show translated text from clipboard as notification
      args:
        - primary-lang:
            short: p
            help: Target language to translate
            required: true
            takes_value: true
            index: 1
        - secondary-lang:
            short: s
            help: Language used to fallback translation
            required: false
            takes_value: true
            index: 2
        - translator:
            short: t
            help: "Translator used. Available translators: 'Google'"
            required: false
            takes_value: true
            index: 3
